### ISSUE TITLE
helpradar.nl email adressen aanmaken

### ISSUE THREAD

**Issue by ferrydeboer** [codefornl/helpradar#16]
@milovanderlinden kunnen we alvast wat email adressen opzetten?

- [x] tips@helpradar.nl (Om als datasource aan Ushahidi te hangen)
- [x] help@helpradar.nl (Dit voor mensen die zelf willen helpen)
- [x] info@helpradar.nl (Voor al het andere, help@helpradar.nl kan wellicht een alias van dit adres zijn)

**Comment by milovanderlinden** [comment]
3x emailbox aangemaakt. Ook info is een eigen adres. Ik kan ook een mailforward aanmaken, maar niet naar het eigen domein (curieus)
