### ISSUE TITLE
Nederlandse vertaling Ushahidi

### ISSUE THREAD

**Issue by milovanderlinden** [codefornl/helpradar#19]
Ik heb gemeld bij het ushahidi transifex team voor de nederlandse vertaling. To be continued.

**Comment by ferrydeboer** [comment]
Ik denk inmiddels wel dat dit geen showstopper moet zijn om echt meer publiek te gaan. Hoe staat dit nu in jouw prioriteiten @milovanderlinden Lijkt mij persoonlijk belangrijker om de email adressen (#16) in de lucht te krijgen.
