### ISSUE TITLE
Ushahidi in eigen huisstijl

### ISSUE THREAD

**Issue by milovanderlinden** [codefornl/helpradar#20]
Op dit moment is Jeroen logo en huisstijl aan het bedenken. Om deze goed te laten landen moet ik aanpassingen doen aan de pattern library http://preview.ushahidi.com/platform-pattern-library/master/ en mogelijk een eigen versie integreren in Ushahidi. Dit issue is als vooronderzoek om te kijken wat dit inhoudt en of dit te integreren is met de technische workflow.

**Comment by ferrydeboer** [comment]
Volgens mij kunnen we dit momenteel wel even als gereed beschouwen tot @milovanderlinden ?

**Comment by ferrydeboer** [comment]
**Breadcrumb issues**
- [ ] Segment hover link is wit op een witte achtergrond
- [ ] '>' heeft zwarte achtergrond.
**Change confirmation dialog**
- [ ] Bij wijzigen van wachtwoord verscheen er een dialog met een rode stip. Ik vermoed dat er iets mis ging. En bij wijzigen vaneen survey zie ik een groene stip, hier staat bij een normale deployment  een wit thumbs up icoon in.
**Survey Edit**
- [ ] De prullenbak is misaligned in the rij van een veld.

**Comment by milovanderlinden** [comment]
Ik kan die van het wachtwoord niet herproduceren, de rest is volgens mij nu opgelost. Wellicht volgende keer losse issues maken? Dat is makkelijker individueel op te lossen.

**Comment by milovanderlinden** [comment]
Nieuw issue gemaakt voor het ontbrekende icoon, rest is opgelost

**Comment by ferrydeboer** [comment]
Lekker bezig!!
