### ISSUE TITLE
Wij Amsterdam scraper verbeteren en aansluiten

### ISSUE THREAD

**Issue by ferrydeboer** [codefornl/helpradar#27]
Om zoveel mogelijk data van wij amsterdam te plukken en invulling te geven aan #18 
Moeten we ook de details van een initiatief ophalen voor zaken als de datum.

## Specificaties
Om in dit stadium kwa naamgeving al zoveel mogelijk aansluiting te realiseren op het [datamodel](https://github.com/codefornl/helpradar/blob/5-setup-basic-data-definition/docs/datamodel.dbml): 

### Data geschraapt
**Gegeven** het initiatief https://wijamsterdam.nl/initiatief/15278
**En** de datum & tijd vandaag is 2020-04-16T13:53:32
**Als** dat gescraped wordt 
**Dan** heeft het veld 'name' de waarde 'Mondkapjes maken vanuit mijn atelier'
**En** heeft het veld 'description' de waarde 'Ik maak vanuit mijn atelier mondkapjes samen met ...'
**En** heeft het veld 'categories' de waarde '(Medische) zorg'
**En** heeft het veld 'adres' de waarde 'Stadsdeel West'
**En** heeft het veld 'latitude' de waarde '52.4017392'
**En** heeft het veld 'longitude' de waarde '4.9153521'
**En** heeft het veld 'organiser' de waarde 'Janne Mooij'
**En** heeft het veld 'url' de waarde 'www.maakeenmondkapje.nl'
**En** heeft het veld 'phone' de waarde ''
**En** heeft het veld 'group' de waarde 'supply'
**En** heeft het veld 'notes' de waarde 'Dit initiatief kan jouw hulp gebruiken!
Wat
Ik heb voor mijn initiatief ook een crowdfunding opgestart om de...'
**En** heeft het veld 'extra_fields' de waarde '{ 'geklapt':'126'}'
**En** heeft het veld 'created_at' de waarde '26-03-2020'
**En** heeft het veld 'source' de waarde 'wijamsterdam.nl'
**En** heeft het veld 'source_uri' de waarde 'https://wijamsterdam.nl/initiatief/15278'
**En** heeft het veld 'scraped_at' de waarde '2020-04-16T13:53:32'

### Scraper getriggerd
Gegeven het eind van iedere de dag
Dan gaat er een trigger af om deze scraper te triggeren

**Comment by jskroodsma** [comment]
Ok een idee: de pagina lijkt volledig statistisch (geen formulieren, buttons, oid). Dus hij hoeft niet perse gescraped te worden, dwz met een browser. Is het niet voldoende op de pagina in z'n geheel te downloaden en te parsen met xpath?

Pseudo-code:
1. GET request op de url https://wijamsterdam.nl/initiatief/15278 => Response
2. Response inlezen als xml-tree=>tree
3. Veldwaarden uitlezen met xpath. name=>tree.xpath('//h1')=>text=>'Mondkapjes maken vanuit mijn atelier'

Ik het het zonet geprobeerd met python en lijkt te werken. 

Vervolgstappen:
*mapping tussen velden en xpath strings
*insert into database
*hosten en scheduling script

**Comment by jskroodsma** [comment]
Notes stand-up 20200421
->platformveld: source_uri
->id: initiatief
