### ISSUE TITLE
Standaardiseer mijnbuurtje.nl scrapers

### ISSUE THREAD

**Issue by ferrydeboer** [codefornl/helpradar#28]
Om zoveel mogelijk waarde te halen van platformen die nu al open zijn
Wil mijnbuurtje.nl afgeleidde website scrapen.

We hebben de volgende websites in kaart die gebruik maken van :
- [x] https://puurpapendrecht.nl/
- [x] https://nijmegen-oost.nl/
- [x] https://maasburen.nl/

## Nijmegen Oost Hulp Aanbod
> Harriët
Boodschappen doen of koken in Hunnerberg
4 april 2020
Hulpaanbod, 2 uur per week
Dinsdag, Woensdag
Nog 48 dagen om te reageren
Thema: #CoronaHulp
Wie kan ik in deze tijden een plezier doen met boodschappen op woensdag? Of een pastamaaltijd op dinsdag? Graag in omgeving Hunnerberg. 

**Gegeven** alle coronahulp initiatieven onder 'https://nijmegen-oost.nl/elkaar-helpen?theme%5B%5D=836' 
En https://nijmegen-oost.nl/elkaar-helpen/1769/boodschappen-doen-of-koken-in-hunnerberg (Zie content hier boven ook voordat het verdwijnt)
**En** de datum & tijd vandaag is 2020-04-16T13:53:32
**Als** dat gescraped wordt 
**Dan** heeft het veld 'name' de waarde 'Boodschappen doen of koken in Hunnerberg'
**En** heeft het veld 'description' de waarde 'Wie kan ik in deze tijden een plezier doen met boodschappen op woensdag? Of een pastamaaltijd op dinsdag? Graag in omgeving Hunnerberg.'
**En** heeft het veld 'categories' de waarde ''
**En** heeft het veld 'adres' de waarde 'Nijmegen Oost'
**En** heeft het veld 'latitude' de waarde ''
**En** heeft het veld 'longitude' de waarde '
**En** heeft het veld 'organiser' de waarde 'Harriët'
**En** heeft het veld 'url' de waarde ''
**En** heeft het veld 'phone' de waarde ''
**En** heeft het veld 'group' de waarde 'supply'
**En** heeft het veld 'notes' de waarde ''
**En** heeft het veld 'frequency' de waarde '{'on':'Dinsdag, Woensdag', 'availability':'2 uur per week'}'
**En** heeft het veld 'created_at' de waarde '06-04-2020'
**En** heeft het veld 'source' de waarde 'nijmegen-oost.nl'
**En** heeft het veld 'source_uri' de waarde 'https://nijmegen-oost.nl/elkaar-helpen/1769/boodschappen-doen-of-koken-in-hunnerberg'
**En** heeft het veld 'scraped_at' de waarde '2020-04-16T13:53:32'

## Puur Papendrecht Hulp Gevraagd
> Nadja Krijgsman
Balkons opfleuren van verpleeghuis de Wieken
25 maart 2020
Hulpvraag, 4 uur
Nog 37 dagen om te reageren
Thema: #CoronaHulp
Vraag vanuit: Organisatie
Het wordt steeds mooier weer, bewoners van de Wieken kunnen heerlijk op hun balkons gaan zitten in de zon, nu er voor hun veel activiteiten uitvallen en zij ook geen bezoek meer kunnen ontvangen, is dit een hele fijne afleiding.

Om wat gezelligheid te brengen in deze periode, wil ik graag de balkons wat opfleuren van de woongroepen. 

Nu staan alle bloembakken nog leeg, hoe leuk is het als deze gevuld kunnen worden met vrolijke voorjaarsbloemen?

Hiervoor vraag ik hulp, hulp met het vullen van de bloembakken en ook om aan voorjaarsbloemen te komen! Wie heeft er leuke ideeën en wie wil er komen helpen? 

**Gegeven** alle coronahulp initiatieven onder 'https://puurpapendrecht.nl/elkaar-helpen?themes_puurpapendrecht_deed%5B%5D=837' 
En het initiatief https://puurpapendrecht.nl/elkaar-helpen/1659/balkons-opfleuren-van-verpleeghuis-de-wieken(Zie content hier boven ook voordat het verdwijnt)
**En** de datum & tijd vandaag is 2020-04-16T13:53:32
**Als** dat gescraped wordt 
**Dan** heeft het veld 'name' de waarde 'hulp voor boodschappen of andere logistieke klusjes'
**En** heeft het veld 'description' de waarde Het wordt steeds mooier weer, bewoners van de Wieken kunnen heerlijk op hun balkons...'
**En** heeft het veld 'categories' de waarde ''
**En** heeft het veld 'adres' de waarde 'Nijmegen Oost'
**En** heeft het veld 'latitude' de waarde ''
**En** heeft het veld 'longitude' de waarde '
**En** heeft het veld 'organiser' de waarde 'Papendrecht'
**En** heeft het veld 'organiser_kind' de waarde 'Organisatie'
**En** heeft het veld 'url' de waarde ''
**En** heeft het veld 'phone' de waarde ''
**En** heeft het veld 'group' de waarde 'demand'
**En** heeft het veld 'notes' de waarde ''
**En** heeft het veld 'created_at' de waarde '25-03-2020'
**En** heeft het veld 'source' de waarde 'https://puurpapendrecht.nl/'
**En** heeft het veld 'source_uri' de waarde 'https://puurpapendrecht.nl/elkaar-helpen/1659/balkons-opfleuren-van-verpleeghuis-de-wieken'
**En** heeft het veld 'scraped_at' de waarde '2020-04-16T13:53:32'

## Scraper getriggered
Gegeven eind van ieder uur
Dan gaat er een trigger af om deze scraper te triggeren
_In principe is dit om ook een vraagverloop te kunnen detecteren. De frequentie zou misschien ook wel wat lager kunnen_

## Implementatie
Dit zou opgelost moeten kunnen worden met één configureerbare scraper. Momenteel zijn er dus twee losse scrapers voor:
* [puurpapendrecht.py](https://github.com/codefornl/helpradar/blob/master/src/scrapers/platformen/puurpapendrecht.py)
* [nijmegenoost.py](https://github.com/codefornl/helpradar/blob/master/src/scrapers/platformen/nijmegenoost.py)

**Comment by jskroodsma** [comment]
@ferrydeboer 

Hey Ferry, als ik het goed begrijp is onderstaand het schema voor puurpapendrecht, met de velden:
 
> En het initiatief https://puurpapendrecht.nl/elkaar-helpen/1659/balkons-opfleuren-van-verpleeghuis-de-wieken(Zie content hier boven ook voordat het verdwijnt)
> En de datum & tijd vandaag is 2020-04-16T13:53:32
> Als dat gescraped wordt
> Dan heeft het veld 'name' de waarde 'hulp voor boodschappen of andere logistieke klusjes'
> En heeft het veld 'description' de waarde Het wordt steeds mooier weer, bewoners van de Wieken kunnen heerlijk op hun balkons...'
> En heeft het veld 'categories' de waarde '' **JKR niet aanwezig**
> En heeft het veld 'adres' de waarde 'Nijmegen Oost' **JKR: kan adres niet vinden**
> En heeft het veld 'latitude' de waarde '' **JKR geen kaartje dus niet relevant**
> En heeft het veld 'longitude' de waarde ' **JKR geen kaartje dus niet relevant**
> En heeft het veld 'organiser' de waarde 'Papendrecht'
> En heeft het veld 'organiser_kind' de waarde 'Organisatie' **JKR: vaste waarde?**
> En heeft het veld 'url' de waarde '' **JKR: uit de source? **
> En heeft het veld 'phone' de waarde '' **JKR: niet aanwezig hier, is het een optioneel veld?**
> En heeft het veld 'group' de waarde 'demand' **JKR: vaste waarde?**
> En heeft het veld 'notes' de waarde '' **JKR: niet aanwezig hier, is het een optioneel veld?**
> En heeft het veld 'created_at' de waarde '25-03-2020'
> En heeft het veld 'source' de waarde 'https://puurpapendrecht.nl/'
> En heeft het veld 'source_uri' de waarde 'https://puurpapendrecht.nl/elkaar-helpen/1659/balkons-opfleuren-van-verpleeghuis-de-wieken'
> En heeft het veld 'scraped_at' de waarde '2020-04-16T13:53:32'

De pagina is:
![image](https://user-images.githubusercontent.com/41111616/80498657-4a0c1300-896c-11ea-807f-4710ba76bb8a.png)

![image](https://user-images.githubusercontent.com/41111616/80498819-80499280-896c-11ea-83f2-145e19b76e5f.png)

Mijn vragen zijn:
1. welke velden zijn verplicht: "Adres" kan ik bvb niet herleiden uit bovenstaande pagina
2. welke velden hebben een constante waarde: bijvoorbeeld het veld "group"="demand"? deze lijkt niet afgeleid te worden uit de pagina zelf? 
3. welke velden zijn conditioneel: bvb latitude/longitude. die kunnen alleen bepaald/gescraped worden conditioneel op de aanwezigheid van een kaartje. of zie ik dat verkeerd?

**Comment by ferrydeboer** [comment]
1. @jskroodsma in principe is alleen de naam en description in Ushahidi verplicht. Ik kon in de database niet direct alles not nullable maken omdat er soms al data in stond en ik dat dus niet kon veranderen en dus ingewikkeld is in de migratie. Maar informeel zijn:
- name
- description
- group
verplicht.
Er zijn in de import_initiatives de volgende velden sowieso verplicht:
- id: _Maar dit hoef je niet zelf te zetten_
- source_uri: in feite kan je dit zien als de external id
- state, maar die wordt default al op imported gezet

2. 
- group kan in principe alleen supply of demand zijn. Dit is in het geval van mijnbuurtje te herleiden uit hulpvraag of hulpaanbod dat je in het lijstje ziet staan. Niet helemaal duidelijk aan de spec zie ik.
- organisation_kind. Ik besef me nu dat dit wat lastiger is. In principe hebben we vier organisatie soorten. Maar dit kunnen we niet 1-op-1 mappen eigenlijk. Want hulpaanbod vanuit organisatie kan nog steeds een bedrijf of een maatschappelijke organisatie zijn en kunnen we niet als zodanig herkennen dus dan maar beter leeg laten.

3. In het geval van mijn buurtje hebben we die informatie niet. Dus daarom staat er in de specs dan bij adres de papendrecht op nijmegen oost. Milo heeft al een keer een script geschreven dat in de tools staat dat die geocode dus dat hoeft niet in de scraper.
