### ISSUE TITLE
Update Ushahidi frond-end naar laatste versie

### ISSUE THREAD

**Issue by ferrydeboer** [codefornl/helpradar#33]
Er was een bug waardoor we geen beschrijvingen aan konden passen in surveys. Dit is gefixt in https://github.com/ushahidi/platform-client/pull/1502.

Voor uitleg van velden is dit erg belangrijk om te hebben. Graag updaten dus naar meeste recente versie van UI.

**Comment by milovanderlinden** [comment]
Done
