### ISSUE TITLE
Email in en out werkt niet.

### ISSUE THREAD

**Issue by ferrydeboer** [codefornl/helpradar#34]
## Scenarios:
- [ ] datasource:outgoing : ??
- [ ] datasource:incoming : email in
- [ ] savedsearch:sync : ??
- [ ] notification:queue : queuen van notificaties (Welke notificaties?)
- [ ] webhook:send : waarschijnlijk wel even te testen met een azure webhook.

## Verzenden
Next Swift_TransportException: Connection to tcp://smtp.transip.email:465 Timed Out in /var/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:473

## Ontvangen
- [x] configuratie

**Comment by milovanderlinden** [comment]
Hiervoor moeten we cronjobs instellen. Ga ik onderzoeken.

**Comment by milovanderlinden** [comment]
Ik heb hem een keer handmatig gerund en ben benieuwd of dit werkt. Zelf zie ik geen mail binnenkomen, maar dat zou correct kunnen zijn.
