### ISSUE TITLE
Introduceer environment variables

### ISSUE THREAD

**Issue by ferrydeboer** [codefornl/helpradar#57]
Om geautomatiseerd te kunnen deployen
Moeten we settings voor environment specifieke configuratie uit environment variabelen lezen.

* Environment variabele moet in src/migrations/env.py ingelezen worden. Deze komt normaal uit de alembic.ini

**Comment by maikelvl** [comment]
@ferrydeboer Bedoel je hiermee database credentials? En welke eventueel nog meer?

**Comment by ferrydeboer** [comment]
@maikelvl Ja vooralsnog alleen die ja. Ik heb deze even aan je PR gelinked alvast.
