### ISSUE TITLE
Scraper deployment script

### ISSUE THREAD

**Issue by ferrydeboer** [codefornl/helpradar#61]
Om nieuwe versies van de scrapers geautomatiseerd te kunnen laten draaien
Als developer
Wil ik dat er een CI/CD pipeline komt waarmee nieuwe versies getest kunnen worden.

## Specificaties
- [ ] Runt tests
Als tests slagen:
- [x] Deploy code 
- [ ] Crontab
- [x] Als ok, run migration (`alembic upgrade head`) (Dit betekent dat migrations niet destructive mogen zijn voor de draaiende versie!)

**Comment by milovanderlinden** [comment]
I have created the first 0.1 version of the Dockerfile. It will initiate the production environment, initialize the database by running the alembic script' show the help info for main.py and exit.

**Comment by milovanderlinden** [comment]
De tests slagen ook al in travis, waarom moeten die dan ook bij de  deploy nog een keer worden gecontroleerd?
