### ISSUE TITLE
Ushahidi deployment inrichten

### ISSUE THREAD

**Issue by ferrydeboer** [codefornl/helpradar#9]
Om eerste validaties te kunnen doen
Wil ik een instantie hebben van Ushahidi waar we alle data kunnen definiëren en testen.

_Deze instance kunnen we propageren tot productie zodra we gereed zijn door test invoer er uit te gooien en enkel definities intact te laten. Een kopie kan dan gaan dienen als een testomgeving. _

**Comment by milovanderlinden** [comment]
Done: site op app.helpradar.nl en api op api.helpradar.nl staan online.
